services:
  web:
    build: .
    container_name: tahmkench
    env_file: ".env"
    volumes:
      - ./static/cache:/usr/src/app/static/cache
    networks:
      - nginx

networks:
  nginx:
    external: true
    name: nginx